# Sync repo to the Codeberg mirror
name: Mirror Sync (GitHub -> Codeberg)
on:
  push:
    branches:
      - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Sync repo"
        uses: cynicsketch/mirror-action@master
        with:
          REMOTE: 'ssh://git@codeberg.org/lasercata/Dotfiles.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          # GIT_SSH_NO_VERIFY_HOST: "true"
